name: Sync Database

on:
  push:
    branches:
      - master
    paths:
      - "music.json" # music.json 파일이 변경될 때만 실행

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # 이전 커밋을 가져오기 위해 필요

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Sync database
        run: pnpm run sync-db
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
